# Generated by Django 2.1 on 2018-08-29 00:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ecaf80fe-9cfe-42bf-a93c-147f1c4a5827'), help_text='id for comment', primary_key=True, serialize=False),
        ),
    ]
