# Generated by Django 2.1 on 2018-08-29 00:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180829_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c7ad5187-b29a-4282-8f37-9c2b4ce86680'), help_text='id for comment', primary_key=True, serialize=False),
        ),
    ]
