# Generated by Django 2.1 on 2018-08-29 00:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180829_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a1e34296-1cc2-4dff-8a68-026e3b5f618c'), help_text='id for comment', primary_key=True, serialize=False),
        ),
    ]
