# Generated by Django 2.1 on 2018-08-29 00:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180829_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c4b7a33c-8998-44f1-bd0c-1e5a7b5cf87a'), help_text='id for comment', primary_key=True, serialize=False),
        ),
    ]
