# Generated by Django 2.1 on 2018-08-29 00:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20180829_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('519b63c7-1aed-4445-8ec1-7d506a3d5ffa'), help_text='id for comment', primary_key=True, serialize=False)),
                ('contents', models.CharField(max_length=1000)),
                ('comment_date', models.DateField(blank=True, default=datetime.date(2018, 8, 29), null=True)),
                ('status', models.CharField(blank=True, choices=[('c', 'censorship'), ('p', 'published')], default='c', help_text='status of comment', max_length=1)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Blog')),
                ('commentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['comment_date'],
            },
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='commentor',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
