# Generated by Django 2.1 on 2018-08-29 00:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180829_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='blog',
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3363ba84-0c7c-4c16-9a8a-219be4121612'), help_text='id for comment', primary_key=True, serialize=False),
        ),
    ]
