# Generated by Django 2.1 on 2018-08-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180829_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(help_text='id for comment', primary_key=True, serialize=False),
        ),
    ]
