# Generated by Django 2.1 on 2018-08-29 06:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180829_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.BlogAuthor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c059950c-db2a-4b35-965f-bce06201bc95'), help_text='id for comment', primary_key=True, serialize=False),
        ),
    ]
